---

name: Publish Docker image
on:
  push:
    branches:
      - debian_stretch
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}    


          #tags: docker.pkg.github.com/${{ github.repository }}/debian:stretch-latest

...
